#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

SERVICE_USE_PID=1

START=50

start() {
	mkdir -m 0755 -p /var/log/lighttpd
	touch /etc/lighttpd.user
	if [ -e "/etc/serial" ]
		then
		echo "polkaspots:`cat /etc/serial`" > /etc/lighttpd/lighttpd.user
	else
		echo "polkaspots:stinky" > /etc/lighttpd/lighttpd.user
	fi
	service_start /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf
}

stop() {
	service_stop /usr/sbin/lighttpd
}

